# Generated by Django 5.2.11 on 2026-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='importance_score',
            field=models.FloatField(default=0.5),
        ),
    ]
